// For todays date;
Date.prototype.today = function () {
    return this.getFullYear() +"-"+ (((this.getMonth()+1) < 10)?"0":"") + (this.getMonth()+1) +"-"+ ((this.getDate() < 10)?"0":"") + this.getDate();
}

// For the time now
Date.prototype.timeNow = function () {
    return ((this.getHours() < 10)?"0":"") + this.getHours() +":"+ ((this.getMinutes() < 10)?"0":"") + this.getMinutes() +":"+ ((this.getSeconds() < 10)?"0":"") + this.getSeconds();
}

let currentdate = new Date();
let currentDateTime =  currentdate.today() + " " + currentdate.timeNow();
client.global.set("currentDateTime", currentDateTime)
client.global.set("authorizationType", "finalAuthorization")
client.global.set("cardAcceptorName", "CMTICKETING")
client.global.set("cardAcceptorCity", "Breda")
client.global.set("cardAcceptorCountry", "NLD")
client.global.set("cardAcceptorPostalCode", "4825BD")
client.global.set("cardAcceptorCategoryCode", "0742")
client.global.set("cardAcceptorId", "123456789012")
client.global.set("threeDSecureEcommerceIndicator", "02")
client.global.set("threeDSecureAuthenticationVerificationValue", "jI3JBkkaQ1p8CBAAABy0CHUAAAA=")
client.global.set("threeDSecureDirectoryServerTransactionId", "3bd2137d-08f1-4feb-ba50-3c2d4401c91a")
client.global.set("threeDSecureVersion", "2")
client.global.set("MastercardCreditcard1Pan", "5204740000001002")
client.global.set("MastercardCreditcard1Holder", "P A Vision VISAAAAA")
client.global.set("MastercardCreditcard1Cvv", "234")
client.global.set("MastercardCreditcard1ExpiryYear", "30")
client.global.set("MastercardCreditcard1ExpiryMonth", "12")
client.global.set("testcard1", "4229989999000012")
client.global.set("testcarde1", "4012001037141112")
client.global.set("testcarde2", "4012001037167778")
client.global.set("testcard12", "4005529999000123")
client.global.set("testcarde3", "4005520000000129")
client.global.set("testcarde13", "4176669999000104")
client.global.set("globalHostTestCard1_holder", "Visa cert card 1")
client.global.set("globalHostTestCard1_pan", "4229989999000012")
client.global.set("globalHostTestCard1_cvv", "871")
client.global.set("globalHostTestCard1_expiryYear", "31")
client.global.set("globalHostTestCard1_expiryMonth", "12")
client.global.set("globalHostTestCard3_holder", "Visa cert card 3")
client.global.set("globalHostTestCard3_pan", "4761349999000039")
client.global.set("globalHostTestCard3_cvv", "998")
client.global.set("globalHostTestCard3_expiryYear", "31")
client.global.set("globalHostTestCard3_expiryMonth", "12")
client.global.set("globalHostTestCard12_holder", "Visa cert card 12")
client.global.set("globalHostTestCard12_pan", "4005529999000123")
client.global.set("globalHostTestCard12_cvv", "196")
client.global.set("globalHostTestCard12_expiryYear", "31")
client.global.set("globalHostTestCard12_expiryMonth", "12")
client.global.set("globalHostTestCardE1_holder", "Visa cert card E-1")
client.global.set("globalHostTestCardE1_pan", "4012001037141112")
client.global.set("globalHostTestCardE1_cvv", "212")
client.global.set("globalHostTestCardE1_expiryYear", "27")
client.global.set("globalHostTestCardE1_expiryMonth", "12")
client.global.set("globalHostTestCardE1_cavv3ds2", "MDA5OTAxMDUyNTExMTEwMDAwMDAwMDc4ODQwMDcwNzAwMDAwMDAwMA==")
client.global.set("globalHostTestCardE1_eci", "05")
client.global.set("globalHostTestCardE2_holder", "Visa cert card E-2")
client.global.set("globalHostTestCardE2_pan", "4012001037167778")
client.global.set("globalHostTestCardE2_cvv", "990")
client.global.set("globalHostTestCardE2_expiryYear", "27")
client.global.set("globalHostTestCardE2_expiryMonth", "12")
client.global.set("globalHostTestCardE2_cavv3ds2", "MDgwMDEwMDc2OTA5ODYwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMA==")
client.global.set("globalHostTestCardE2_eci", "06")
client.global.set("globalHostTestCardE3_holder", "Visa cert card E-3")
client.global.set("globalHostTestCardE3_pan", "4005520000000129")
client.global.set("globalHostTestCardE3_cvv", "986")
client.global.set("globalHostTestCardE3_expiryYear", "27")
client.global.set("globalHostTestCardE3_expiryMonth", "12")
client.global.set("globalHostTestCardE3_cavv3ds2", "MDQwMTAxMDY1OTExMTEwMDAwMDAxMzg4ODQwMDcwNzAwMDAwMDAwMA==")
client.global.set("globalHostTestCardE3_eci", "07")
client.global.set("globalHostTestCardE13_holder", "Visa cert card E-13")
client.global.set("globalHostTestCardE13_pan", "4176669999000104")
client.global.set("globalHostTestCardE13_cvv", "012")
client.global.set("globalHostTestCardE13_expiryYear", "31")
client.global.set("globalHostTestCardE13_expiryMonth", "12")
client.global.set("globalHostTestCardE13_cavv", "MDAwMDAxMDM2NzExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMA==")
client.global.set("globalHostTestCardE13_eci", "05")
client.global.set("directoryServerID", "3bd2137d-08f1-4feb-ba50-3c2d4401c91a")
client.global.set("WrongCAVVFor3DS", "MDAwMDAyMDk5OTk5OTk4MzAxMjA1MzAxNjYxMjI0MDAwMDAwMDAwMA==")
client.global.set("WrongCAVVFor3DSAttempt", "MDgwMDEwMDk5OTk5OTk3ODU5MTczMjg5NjIwOTg2MDAwMDAwMDAwMA==")