###
# @name=Authorize initial recurring

< ../date.js

POST {{host}}/v1/authorizations/
Content-Type: application/json
nonce: gw-{{$random.uuid}}
Authorization: Basic {{authorization_perm}}

{
    "amount": {{$random.integer(100, 200)}},
    "currency": "EUR",
    "reference": "{{$random.uuid}}",
    "source": "ecommerce",
    "localTransactionDateTime": "{{currentDateTime}}",
    "initialRecurring": true,
    "authorizationType": "finalAuthorization",
    "card": {
        "holder": "{{$random.alphabetic(10)}}",
        "number": "5204740000001002",
        "cvv": "390",
        "expiry": {
            "year": "24",
            "month": "12"
        }
    },
    "cardAcceptor": {
        "id": "CMTICKETING",
        "categoryCode": "5411",
        "name": "cm-ticketing",
        "city": "Breda",
        "country": "NLD",
        "postalCode": "4847CV"
    },
    "threeDSecure": {
        "authenticationVerificationValue": "AAABBWcSNIdjeUZThmNHAAAAAAA=",
        "version": "2",
        "ecommerceIndicator": "02",
        "directoryServerTransactionId": "842e6686-b40c-4efd-aed5-a32c589589aa"
    },
    "citMitIndicator": {
        "initiatedBy": "cardholder",
        "subCategory": "credentialOnFile"
    }
}

> {%
    client.test("Authorize initial recurring should return 200 OK", function () {
        client.assert(response.status === 200, "status is not 200")
    })

    client.test("Authorize initial recurring cardschemeresponse code should be 00", function (){
        client.assert(response.body.cardSchemeResponse.code == "00")
    })

    client.test("AuthorizationID should be set", function () {
        client.assert(response.body.id != "")
    })

    if (response.status === 200) {
        client.global.clear("amount")
        client.global.clear("authorization_id")
        client.global.clear("reference")
        client.global.clear("currency")
        client.global.clear("initialTraceId");
        client.global.set("initialTraceId", response.body.cardSchemeResponse.traceId);
        client.global.set("amount", response.body.amount)
        client.global.set("currency", response.body.currency)
        client.global.set("authorization_id", response.body.id)
        client.global.set("reference", response.body.reference)
    }
%}