// Code generated by timing/wrappers/generate, DO NOT EDIT.
// Generated on Mon May 15 15:07 2023
package timingwrappers

import (
	"context"
	app "gitlab.cmpayments.local/creditcard/authorization/internal/authorization/app"
	entity "gitlab.cmpayments.local/creditcard/authorization/internal/entity"
	timing "gitlab.cmpayments.local/creditcard/authorization/internal/timing"
)

type AuthorizationTokenizer struct {
	Base app.Tokenizer
}

func (w AuthorizationTokenizer) Detokenize(ctx context.Context, merchantID string, card entity.Card) (entity.Card, error) {
	timing.Start(ctx, "AuthorizationTokenizer.Detokenize")
	defer timing.Stop(ctx, "AuthorizationTokenizer.Detokenize")
	return w.Base.Detokenize(ctx, merchantID, card)
}
func (w AuthorizationTokenizer) Tokenize(ctx context.Context, merchantID string, card entity.Card) (string, error) {
	timing.Start(ctx, "AuthorizationTokenizer.Tokenize")
	defer timing.Stop(ctx, "AuthorizationTokenizer.Tokenize")
	return w.Base.Tokenize(ctx, merchantID, card)
}
