// Code generated by timing/wrappers/generate, DO NOT EDIT.
// Generated on Mon May 15 15:07 2023
package timingwrappers

import (
	"context"
	timing "gitlab.cmpayments.local/creditcard/authorization/internal/timing"
	pubsub "gitlab.cmpayments.local/creditcard/platform/events/pubsub"
)

type Publisher struct {
	Base pubsub.Publisher
}

func (w Publisher) Publish(ctx context.Context, topic string, p pubsub.Publishable) error {
	timing.Start(ctx, "Publisher.Publish")
	defer timing.Stop(ctx, "Publisher.Publish")
	return w.Base.Publish(ctx, topic, p)
}
