// Code generated by timing/wrappers/generate, DO NOT EDIT.
// Generated on Mon May 15 15:07 2023
package timingwrappers

import (
	"context"
	entity "gitlab.cmpayments.local/creditcard/authorization/internal/entity"
	app "gitlab.cmpayments.local/creditcard/authorization/internal/reversal/app"
	timing "gitlab.cmpayments.local/creditcard/authorization/internal/timing"
)

type ReversalRepository struct {
	Base app.ReversalRepository
}

func (w ReversalRepository) CreateReversal(ctx context.Context, reversal entity.Reversal) error {
	timing.Start(ctx, "ReversalRepository.CreateReversal")
	defer timing.Stop(ctx, "ReversalRepository.CreateReversal")
	return w.Base.CreateReversal(ctx, reversal)
}
func (w ReversalRepository) UpdateReversalResponse(ctx context.Context, reversal entity.Reversal) error {
	timing.Start(ctx, "ReversalRepository.UpdateReversalResponse")
	defer timing.Stop(ctx, "ReversalRepository.UpdateReversalResponse")
	return w.Base.UpdateReversalResponse(ctx, reversal)
}
