###
# @name = Capture Authorization
POST {{host}}/v1/authorizations/{{authorization_id}}/captures/
Content-Type: application/json
nonce: gw-{{$random.uuid}}
Authorization: Basic {{authorization_perm}}

{
    "amount": {{amount}},
    "currency": "{{currency}}",
    "isFinal": true,
    "reference": "{{reference}}"
}

> {%
    client.test("Capture Authorization should return 201 OK", function () {
        client.assert(response.status === 201, "status is not 201")
    })
%}